app.py
import os
from flask import Flask  

def create_app():
    
    app = Flask(__name__)
    app.secret_key = os.urandom( 24 )   # 'N0tu5'

    from views import main
    app.register_blueprint(main)
    return app 

views.py
import functools
# from formularios import formularioMensaje
from flask import Flask, abort, render_template, blueprints, request, jsonify, redirect, url_for,session, flash, send_file
from werkzeug.security import check_password_hash, generate_password_hash
from db import get_db
from markupsafe import escape
from mensaje import mensajes


#creo el objeto que representa la aplicacion 
main = blueprints.Blueprint('main', __name__) #esto es un constructor - , url_prefix='/home'

def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if 'usuario' not in session: #puedes hacer otro tipo de validación 
            return redirect(url_for('main.home'))
        return view(**kwargs)

    return wrapped_view

# creo las rutas - con cualquiera de estos alias voy a acceder a la pagima principal del sitio 

@main.route('/')    # Aqui aterriza el usuario cuando se dirige a la app, y es redireccionado al home
def site():         # desde aqui puede ser redireccionado donde se desee y puede ejecutarse el codigo que se 
    return redirect(url_for('main.home'))   # requiera a modo de setup

@main.route('/home/', methods=['GET', 'POST'])
def home():

    '''if(request.method == 'POST'):

        Accion = request.form['Boton']

        if(Accion == 'login'):      # Boton login pulsado -> redirecciona al formulario de login
            return redirect(url_for('main.login'))

        if(Accion == 'signUp'):      # Boton login pulsado -> redirecciona al formulario de login
            return redirect(url_for('main.signUp'))'''

    return render_template('home.html')

@main.route('/login/', methods=['GET', 'POST'])
def login():

    '''if(request.method == 'POST'): 

        usuario= request.form['username']
        clave = request.form['userPassword']
        Accion = request.form['Boton']

        if(Accion == 'login'):      # Boton iniciar sesion pulsado -> me direcciona al index de la app
            
            # return redirect(url_for('main.index'))
            if(usuario =='notus' and clave =='notus'):
                # return redirect(url_for('main.listadoMensajes')) # Aquise programa lo que debe hacer cuando el login sea exitoso
                return redirect(url_for('main.index'))

    return render_template('login.html') '''

    if request.method =='POST':

        usuario = escape(request.form['username'])
        clave = escape(request.form['userPassword'])

        db = get_db()
        #sql = "select * from usuario where usuario = '{0}' and clave= '{1}'".format(usuario, clave)

        # numUsers = db.execute('SELECT count(*) FROM Persona').fetchone()
        # if(numUsers == 0):
        # print(numUsers)

        user = db.execute('select * from Persona where username = ? ', (usuario,)).fetchone()
        db.commit()
        db.close()

        if user is not None:

            clave = clave + usuario
            
            sw = check_password_hash(user[9], clave)
            if(sw):

                session['nombre'] = user[3]
                session['apellido'] = user[4]
                session['usuario'] = user[8]
                session['role'] = user[12]

                return redirect(url_for('main.index'))
        flash('Usuario o clave incorrecto.', 'errorLogin') 
    return render_template('login.html')

@main.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('main.home'))

@main.route('/resetPassword/', methods=['GET', 'POST'])
def resetPassword():

    if(request.method == 'POST'):
        return redirect(url_for('main.resetPasswordOK'))

    return render_template('password_reset.html')

@main.route('/resetPasswordOK/', methods=['GET', 'POST'])
def resetPasswordOK():

    if(request.method == 'POST'):
            return redirect(url_for('main.home'))

    return render_template('password_reset_OK.html')

@main.route('/listado_Mensajes/')
def listadoMensajes():
    return jsonify(mensajes)

@main.route('/testAjax/')
def testAjax():
    return render_template('testAjax.html')

@main.route('/index/', methods=['GET', 'POST'])
@login_required
def index():
    return render_template('index2.html')

@main.route('/index/usuario/', methods=['GET', 'POST'])
@login_required
def usuario():
    return render_template('usuario.html')

@main.route('/index/crearUsuario/', methods=['GET', 'POST'])
@login_required
def crearUsuario():

    # Accion = request.form['Boton']
    # print(Accion)
    if (request.method == 'POST'): # and request.form['Boton'] == 'Create'):

        nombresUsuario = escape(request.form['nombresUsuario'])
        apellidosUsuario = escape(request.form['apellidosUsuario'])
        tipoDocumento = escape(request.form['tipoDocumento'])
        numeroDocumento = escape(request.form['numeroDocumento'])
        fechaNacimiento = escape(request.form['fechaNacimiento'])
        sexo = escape(request.form['sexo'])
        telefonoUsuario = escape(request.form['telefonoUsuario'])
        mailUsuario = escape(request.form['mailUsuario'])
        userName = escape(request.form['userName'])
        userPassword = escape(request.form['userPassword'])
        roll = escape(request.form['roll'])
        condiciones = escape(request.form['condiciones'])

        print(userName)
        print(userPassword)

        db = get_db()
        #agregar SALT
        #clave = SALT + clave + usuario
        userPassword = userPassword + userName 
        userPassword = generate_password_hash(userPassword)
        db.execute("INSERT into Persona ( numeroDocumento, tipoDocumento, nombres, apellidos, telefono, sexo, correo, username, password, estadoPersona, fechaNacimiento, roll) values( ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)",(numeroDocumento, tipoDocumento, nombresUsuario, apellidosUsuario, telefonoUsuario, sexo, mailUsuario, userName, userPassword, 'True', fechaNacimiento, roll))
        db.commit()
        db.close()

        return redirect(url_for('main.usuario'))
        
    return render_template('usuario_crear.html')

@main.route('/index/buscarUsuario/', methods=['GET', 'POST'])
@login_required
def buscarUsuario():
    return render_template('usuario_buscar.html')

@main.route('/index/editarUsuario/', methods=['GET', 'POST'])
@login_required
def editarUsuario():
    return render_template('usuario_editar.html')

@main.route('/index/eliminarUsuario/', methods=['GET', 'POST'])
@login_required
def eliminarUsuario():
    return render_template('usuario_eliminar.html')

@main.route('/index/cursos/', methods=['GET', 'POST'])
@login_required
def cursos():
    return render_template('cursos.html')

@main.route('/index/cursos/crearCurso/', methods=['GET', 'POST'])
@login_required
def crearCurso():
    return render_template('cursos_crear.html')

@main.route('/index/cursos/buscarCurso/', methods=['GET', 'POST'])
@login_required
def buscarCurso():
    return render_template('cursos_buscar.html')

@main.route('/index/cursos/consultarCurso/', methods=['GET', 'POST'])
@login_required
def consultarCurso():
    return render_template('cursos_consultar.html')

@main.route('/index/cursos/editarCurso/', methods=['GET', 'POST'])
@login_required
def editarCurso():
    return render_template('cursos_editar.html')

@main.route('/index/cursos/eliminarCurso/', methods=['GET', 'POST'])
@login_required
def eliminarCurso():
    return render_template('cursos_eliminar.html')

@main.route('/index/cursos/calificarCurso/', methods=['GET', 'POST'])
@login_required
def calificarCurso():
    return render_template('cursos_calificar.html')

@main.route('/index/cursos/consultarCalificaciones/', methods=['GET', 'POST'])
@login_required
def consultarCalificaciones():
    return render_template('calificaciones_consultar.html')

@main.route('/index/materias/', methods=['GET', 'POST'])
@login_required
def materias():
    return render_template('materias.html')

@main.route('/index/crear_materias/', methods=['GET', 'POST'])
@login_required
def crear_materias():
    return render_template('materias_crear.html')

@main.route('/index/editar_materias/', methods=['GET', 'POST'])
@login_required
def editar_materias():
    return render_template('materias_editar.html')

@main.route('/index/eliminar_materias/', methods=['GET', 'POST'])
@login_required
def eliminar_materias():
    return render_template('materias_eliminar.html')

@main.route('/index/buscar_materias/', methods=['GET', 'POST'])
@login_required
def buscar_materias():
    return render_template('materias_buscar.html')

@main.route('/index/actividades/', methods=['GET', 'POST'])
@login_required
def actividades():
    return render_template('actividades.html')

@main.route('/index/comentarios/', methods=['GET', 'POST'])
@login_required
def comentarios():
    return render_template('comentarios.html')

templates/buscar_materias.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menú lateral responsive - MagtimusPro</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css') }}">

    <script src="https://kit.fontawesome.com/41bcea2ae3.js" crossorigin="anonymous"></script>
</head>
<body id="body">
    
    <header>
        <div class="icon__menu">
            <i class="fas fa-bars" id="btn_open"></i>
        </div>
    </header>

    <div class="menu__side" id="menu_side">

        <div class="name__page">
            <i class="fas fa-angle-double-left"></i>
            <h4>NOTUS</h4>
        </div>

        <div class="options__menu">	

            <a href="/index/" >
                <div class="option">
                    <i class="fas fa-home" title="Inicio"></i>
                    <h4>Inicio</h4>
                </div>
            </a>

            <a href="/index/usuario/">
                <div class="option">
                    <i class="far fa-user" title="Usuario"></i>
                    <h4>Usuarios</h4>
                </div>
            </a>
            
            <a href="/index/cursos/" > 
                <div class="option">
                    <i class="fas fa-book" title="Cursos"></i>
                    <h4>Cursos</h4>
                </div>
            </a>

            <a href="/index/materias/" class="selected"> 
                <div class="option">
                    <i class="fas fa-book-open" title="Materias"></i>
                    <h4>Materias</h4>
                </div>
            </a>

            <a href="/index/actividades/">
                <div class="option">
                    <i class="far fa-file" title="Actividades"></i>
                    <h4>Actividades</h4>
                </div>
            </a>

            <a href="/index/comentarios">
                <div class="option">
                    <i class="far fa-comment-alt" title="Comentarios"></i>
                    <h4>Comentarios</h4>
                </div>
            </a>

        </div>

    </div>

    <main>
        <h1>buscar_materias</h1><br>
        
    <form name="buscar_materias" method="POST" action="" >
      
      <p>parametro de busqueda: 
        <div class="input_Container">
          <input type="search" name="busqueda" id="busqueda" form="parametro de busqueda">
        </div>
      </p>

      <button type="submit" name="Boton" value="Cancelar" >
        Cancelar
      </button>

      <button type="submit" name="Boton" value="buscar" >
        buscar
      </button>


    </form>

  </body>
    </main>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    
</body>
</html>

templates/calificaciones_consultar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menú lateral responsive - MagtimusPro</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css') }}">

    <script src="https://kit.fontawesome.com/41bcea2ae3.js" crossorigin="anonymous"></script>
</head>
<body id="body">
    
    <header>
        <div class="icon__menu">
            <i class="fas fa-bars" id="btn_open"></i>
        </div>
    </header>

    <div class="menu__side" id="menu_side">

        <div class="name__page">
            <i class="fas fa-angle-double-left"></i>
            <h4>NOTUS</h4>
        </div>

        <div class="options__menu">	

            <a href="/index/" >
                <div class="option">
                    <i class="fas fa-home" title="Inicio"></i>
                    <h4>Inicio</h4>
                </div>
            </a>

            <a href="/index/usuario/">
                <div class="option">
                    <i class="far fa-user" title="Usuario"></i>
                    <h4>Usuarios</h4>
                </div>
            </a>
            
            <a href="/index/cursos/" class="selected"> 
                <div class="option">
                    <i class="fas fa-book" title="Cursos"></i>
                    <h4>Cursos</h4>
                </div>
            </a>

            <a href="/index/materias/">
                <div class="option">
                    <i class="fas fa-book-open" title="Materias"></i>
                    <h4>Materias</h4>
                </div>
            </a>

            <a href="/index/actividades/">
                <div class="option">
                    <i class="far fa-file" title="Actividades"></i>
                    <h4>Actividades</h4>
                </div>
            </a>

            <a href="/index/comentarios">
                <div class="option">
                    <i class="far fa-comment-alt" title="Comentarios"></i>
                    <h4>Comentarios</h4>
                </div>
            </a>

        </div>

    </div>

    <main>
        <h1>Consultar Calificaciones</h1><br>
        <p>ID curso:</p>
        <input type="text" name="texto" value="###" readonly><br>
        <p>Nombre del curso:</p>
        <input type="text" name="texto" value="..." readonly><br>
        <p>Calificaciones:</p>
        <input type="text" name="texto" value="calificaciones" readonly><br><br><br>
        <button type="button" name="salir" value="Salir" > Salir</button>
    </main>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    
</body>
</html>

templates/comentarios.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menú lateral responsive - MagtimusPro</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css') }}">

    <script src="https://kit.fontawesome.com/41bcea2ae3.js" crossorigin="anonymous"></script>
</head>
<body id="body">
    
    <header>
        <div class="icon__menu">
            <i class="fas fa-bars" id="btn_open"></i>
        </div>
    </header>

    <div class="menu__side" id="menu_side">

        <div class="name__page">
            <i class="fas fa-angle-double-left"></i>
            <h4>NOTUS</h4>
        </div>

        <div class="options__menu">	

            <a href="/index/" >
                <div class="option">
                    <i class="fas fa-home" title="Inicio"></i>
                    <h4>Inicio</h4>
                </div>
            </a>

            <a href="/index/usuario/">
                <div class="option">
                    <i class="far fa-user" title="Usuario"></i>
                    <h4>Usuarios</h4>
                </div>
            </a>
            
            <a href="/index/cursos/" > 
                <div class="option">
                    <i class="fas fa-book" title="Cursos"></i>
                    <h4>Cursos</h4>
                </div>
            </a>

            <a href="/index/materias/">
                <div class="option">
                    <i class="fas fa-book-open" title="Materias"></i>
                    <h4>Materias</h4>
                </div>
            </a>

            <a href="/index/actividades/">
                <div class="option">
                    <i class="far fa-file" title="Actividades"></i>
                    <h4>Actividades</h4>
                </div>
            </a>

            <a href="/index/comentarios" class="selected">
                <div class="option">
                    <i class="fas fa-comment-alt" title="Comentarios"></i>
                    <h4>Comentarios</h4>
                </div>
            </a>

            <a href="{{url_for('main.logout')}}">
                <div class="option">
                    <i class="fas fa-sign-out-alt" title="Cerrar Sesión"></i>
                    <h4>Cerrar Sesión</h4>
                </div>
            </a>

        </div>

    </div>

    <main>
        <h1>Comentarios</h1><br>
    </main>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    
</body>
</html>

templates/cursos_buscar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menú lateral responsive - MagtimusPro</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css') }}">

    <script src="https://kit.fontawesome.com/41bcea2ae3.js" crossorigin="anonymous"></script>
</head>
<body id="body">
    
    <header>
        <div class="icon__menu">
            <i class="fas fa-bars" id="btn_open"></i>
        </div>
    </header>

    <div class="menu__side" id="menu_side">

        <div class="name__page">
            <i class="fas fa-angle-double-left"></i>
            <h4>NOTUS</h4>
        </div>

        <div class="options__menu">	

            <a href="/index/" >
                <div class="option">
                    <i class="fas fa-home" title="Inicio"></i>
                    <h4>Inicio</h4>
                </div>
            </a>

            <a href="/index/usuario/">
                <div class="option">
                    <i class="far fa-user" title="Usuario"></i>
                    <h4>Usuarios</h4>
                </div>
            </a>
            
            <a href="/index/cursos/" class="selected"> 
                <div class="option">
                    <i class="fas fa-book" title="Cursos"></i>
                    <h4>Cursos</h4>
                </div>
            </a>

            <a href="/index/materias/">
                <div class="option">
                    <i class="fas fa-book-open" title="Materias"></i>
                    <h4>Materias</h4>
                </div>
            </a>

            <a href="/index/actividades/">
                <div class="option">
                    <i class="far fa-file" title="Actividades"></i>
                    <h4>Actividades</h4>
                </div>
            </a>

            <a href="/index/comentarios">
                <div class="option">
                    <i class="far fa-comment-alt" title="Comentarios"></i>
                    <h4>Comentarios</h4>
                </div>
            </a>

        </div>

    </div>

    <main>
        <h1>Buscar Curso</h1><br>
        <p>Por favor ingrese el ID o nombre del curso que desea buscar:</p> <br>
        <p><input type="text" name="buscar" size="40" placeholder="Parámetro de búsqueda"></p>
        <button type="button" name="Boton" value="buscarCurso" > Buscar</button><br>
    
    </main>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    
</body>
</html>

templates/cursos_consultar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menú lateral responsive - MagtimusPro</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css') }}">

    <script src="https://kit.fontawesome.com/41bcea2ae3.js" crossorigin="anonymous"></script>
</head>
<body id="body">
    
    <header>
        <div class="icon__menu">
            <i class="fas fa-bars" id="btn_open"></i>
        </div>
    </header>

    <div class="menu__side" id="menu_side">

        <div class="name__page">
            <i class="fas fa-angle-double-left"></i>
            <h4>NOTUS</h4>
        </div>

        <div class="options__menu">	

            <a href="/index/" >
                <div class="option">
                    <i class="fas fa-home" title="Inicio"></i>
                    <h4>Inicio</h4>
                </div>
            </a>

            <a href="/index/usuario/">
                <div class="option">
                    <i class="far fa-user" title="Usuario"></i>
                    <h4>Usuarios</h4>
                </div>
            </a>
            
            <a href="/index/cursos/" class="selected"> 
                <div class="option">
                    <i class="fas fa-book" title="Cursos"></i>
                    <h4>Cursos</h4>
                </div>
            </a>

            <a href="/index/materias/">
                <div class="option">
                    <i class="fas fa-book-open" title="Materias"></i>
                    <h4>Materias</h4>
                </div>
            </a>

            <a href="/index/actividades/">
                <div class="option">
                    <i class="far fa-file" title="Actividades"></i>
                    <h4>Actividades</h4>
                </div>
            </a>

            <a href="/index/comentarios">
                <div class="option">
                    <i class="far fa-comment-alt" title="Comentarios"></i>
                    <h4>Comentarios</h4>
                </div>
            </a>

        </div>

    </div>

    <main>
        <h1>Consultar Curso</h1><br>
        <p>La información del curso seleccionado es:</p> <br>
        <p>ID curso:</p>
        <input type="text" name="texto" value="###" readonly><br>
        <p>Nombre del curso:</p>
        <input type="text" name="texto" value="..." readonly><br><br>
        <textarea rows="5" cols="40" name="descripción" placeholder="Descripción del curso" readonly></textarea> <br>
        <p>Fecha de creación:</p>
        <input type="text" name="texto" value="DD/MM/AAAA" readonly><br>
        <p>Fecha de modificación:</p>
        <input type="text" name="texto" value="DD/MM/AAAA" readonly><br>
        <p>Estado del curso:</p>
        <input type="text" name="texto" value="Activo/Inactivo" readonly><br><br>
        
        <button type="button" name="salir" value="Salir" > Salir</button>    
    </main>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    
</body>
</html>

templates/cursos_eliminar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menú lateral responsive - MagtimusPro</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css') }}">

    <script src="https://kit.fontawesome.com/41bcea2ae3.js" crossorigin="anonymous"></script>
</head>
<body id="body">
    
    <header>
        <div class="icon__menu">
            <i class="fas fa-bars" id="btn_open"></i>
        </div>
    </header>

    <div class="menu__side" id="menu_side">

        <div class="name__page">
            <i class="fas fa-angle-double-left"></i>
            <h4>NOTUS</h4>
        </div>

        <div class="options__menu">	

            <a href="/index/" >
                <div class="option">
                    <i class="fas fa-home" title="Inicio"></i>
                    <h4>Inicio</h4>
                </div>
            </a>

            <a href="/index/usuario/">
                <div class="option">
                    <i class="far fa-user" title="Usuario"></i>
                    <h4>Usuarios</h4>
                </div>
            </a>
            
            <a href="/index/cursos/" class="selected"> 
                <div class="option">
                    <i class="fas fa-book" title="Cursos"></i>
                    <h4>Cursos</h4>
                </div>
            </a>

            <a href="/index/materias/">
                <div class="option">
                    <i class="fas fa-book-open" title="Materias"></i>
                    <h4>Materias</h4>
                </div>
            </a>

            <a href="/index/actividades/">
                <div class="option">
                    <i class="far fa-file" title="Actividades"></i>
                    <h4>Actividades</h4>
                </div>
            </a>

            <a href="/index/comentarios">
                <div class="option">
                    <i class="far fa-comment-alt" title="Comentarios"></i>
                    <h4>Comentarios</h4>
                </div>
            </a>

        </div>

    </div>

    <main>
        <h1>Eliminar Curso</h1><br>
        <p>¿Está seguro que desea eliminar el curso seleccionado?:</p> <br>
        <button type="submit" name="Boton" value="cancelar" > Cancelar</button>
        <button type="submit" name="Boton" value="eliminar" > Eliminar</button><br>
    </main>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    
</body>
</html>

templates/login.html
<html>

  <head>
    <meta charset="UTF-8" />
    <title>Iniciar Sesión</title>
    <script src="{{ url_for('static', filename='js/funciones.js') }}"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/mioCSS.css') }}" />
  </head>

  <body>
    <img src="{{ url_for('static', filename='img/logoNotus.png') }}" />
    <h1>Iniciar Sesión</h1>

    <form name="login" method="POST" >
      
      <p>Usuario: 
        <div class="input_Container">
          <input type="text" name="username" id="username" />
          <img src="{{ url_for('static', filename='img/user.png') }}" class="userIcon"/>
        </div>
        <span class="error" id="errorUsername"></span>
      </p>

      <p>Contraseña:
        <div class="input_Container">
          <input type="password" name="userPassword" />
          <img src="{{ url_for('static', filename='img/key.png')}}" class="userIcon"/>
        </div>
        <span class="error" id="errorPassword"></span>
        <img src="{{ url_for('static', filename='img/ver.png')}}" width=100 height=50 onmouseover="verClave();" onmouseout="ocultarClave()"/>
      </p>
      
      <button type="submit" name="Boton" value="login" method="POST">Iniciar Sesión</button>

      <a href="{{ url_for('main.home')}}">
        <button type="button" name="Boton" value="Cancelar"> Cancelar </button>
      </a>

      <h4></h4>

      <a href="{{ url_for('main.resetPassword')}}">
        <button type="button" name="Boton" value="resetPassword"> Olvide mi contraseña </button>
      </a>

    </form>

  </body>

</html>

templates/usuario.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Menú lateral responsive - MagtimusPro</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilos.css') }}">

    <script src="https://kit.fontawesome.com/41bcea2ae3.js" crossorigin="anonymous"></script>
</head>
<body id="body" >
    
    <header>
        <div class="icon__menu">
            <i class="fas fa-bars" id="btn_open"></i>
        </div>
    </header>

    <div class="menu__side" id="menu_side">

        <div class="name__page">
            <i class="fas fa-angle-double-left"></i>
            <h4>NOTUS</h4>
        </div>

        <div class="options__menu">	

            <a href="/index/" >
                <div class="option">
                    <i class="fas fa-home" title="Inicio"></i>
                    <h4>Inicio</h4>
                </div>
            </a>

            <a href="/index/usuario/" class="selected">
                <div class="option">
                    <i class="fas fa-user" title="Usuario"></i>
                    <h4>Usuarios</h4>
                </div>
            </a>
            
            <a href="/index/cursos/" > 
                <div class="option">
                    <i class="fas fa-book" title="Cursos"></i>
                    <h4>Cursos</h4>
                </div>
            </a>

            <a href="/index/materias/">
                <div class="option">
                    <i class="fas fa-book-open" title="Materias"></i>
                    <h4>Materias</h4>
                </div>
            </a>

            <a href="/index/actividades/">
                <div class="option">
                    <i class="far fa-file" title="Actividades"></i>
                    <h4>Actividades</h4>
                </div>
            </a>

            <a href="/index/comentarios">
                <div class="option">
                    <i class="far fa-comment-alt" title="Comentarios"></i>
                    <h4>Comentarios</h4>
                </div>
            </a>

            <a href="{{url_for('main.logout')}}">
                <div class="option">
                    <i class="fas fa-sign-out-alt" title="Cerrar Sesión"></i>
                    <h4>Cerrar Sesión</h4>
                </div>
            </a>
            
        </div>
    </div>

    <main>
        <h1>Usuario</h1>
        <p>Lista de usuarios existentes:</p> <br>
        <fieldset>
            <article>
                <section>Comentarios </section>
                <section>Columna 1 </section>
                <section>Columna 2 </section>
                <section>Columna 3 </section>
                <section>Columna 4 </section>
                <section>Comentario 1 </section>
                <section> </section>
                <section> </section>
                <section> </section>
                <section> </section>
                <section>Comentario 2 </section>
                <section> </section>
                <section> </section>
                <section> </section>
                <section> </section>
                <section>Comentario 3 </section>
                <section> </section>
                <section> </section>
                <section> </section>
                <section> </section>
                <section>Comentario 4 </section>
                <section> </section>
                <section> </section>
                <section> </section>
                <section> </section>
            </article>
        </fieldset>
        <br>
        
        <form method="POST">
            <a href="{{ url_for('main.crearUsuario')}}">
                <button type="button" name="Boton" value="crearUsuario" > Crear Usuario </button>
            </a>

            <a href="{{ url_for('main.buscarUsuario')}}">
                <button type="button" name="Boton" value="buscarUsuario" > Buscar Usuario </button>
            </a>

            <a href="{{ url_for('main.editarUsuario')}}">
                <button type="button" name="Boton" value="editarUsuario" > Editar Usuario </button>
            </a>

            <a  href="{{ url_for('main.eliminarUsuario')}}">
                <button type="button" name="Boton" value="eliminarUsuario" > Eliminar Usuario </button>
            </a>
        </form>
    </main>

    <script src="{{ url_for('static', filename='js/script.js') }}"></script>
    
</body>
</html>